INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('LADA Granta', 598900);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('LADA Vesta', 862900);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('KIA Rio', 984900);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Hyundai Creta', 1309000);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Hyundai Solaris', 975000);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('VW Polo', 1620900);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('LADA Largus', 829900);